// ============================================================
// Données démo — utilisé en fallback si Supabase n'est pas configuré
// ou si aucune réponse n'est disponible.
// ============================================================

import type { Prospect, DashboardStats } from '@/types';

const now = Date.now();
const day = 86_400_000;

export const demoProspects: Prospect[] = [
  {
    id: 'demo-1',
    created_at: new Date(now - 2 * day).toISOString(),
    updated_at: new Date(now - 2 * day).toISOString(),
    nom: 'Dubois',
    prenom: 'Marie',
    email: 'marie.dubois@example.fr',
    telephone: '06 12 34 56 78',
    adresse: '14 rue de la Loge',
    ville: 'Montpellier',
    code_postal: '34000',
    latitude: 43.6108,
    longitude: 3.8767,
    surface_toit_m2: 78.5,
    nb_panneaux_recommande: 12,
    production_annuelle_kwh: 4850,
    heures_ensoleillement: 2680,
    orientation_principale: 'Sud',
    score_solaire: 92,
    qualite_imagerie: 'HIGH',
    panneaux_detectes: 'non',
    date_photo_satellite: 'mars 2024',
    puissance_kwc: 4.86,
    cout_installation_ttc: 11900,
    aides_totales: 1150,
    reste_a_charge: 10750,
    economie_annuelle: 1380,
    temps_retour_ans: 7.8,
    co2_evite_kg_an: 277,
    statut: 'proposition_envoyee',
    notes: 'Maison individuelle 110m², toiture 4 pans. Très chaud.',
    proposition_id: 'prop_demo_001',
    proposition_html: null,
    proposition_vue_at: null,
  },
  {
    id: 'demo-2',
    created_at: new Date(now - 5 * day).toISOString(),
    updated_at: new Date(now - 5 * day).toISOString(),
    nom: 'Martin',
    prenom: 'Jean-Pierre',
    email: 'jp.martin@example.fr',
    telephone: '06 23 45 67 89',
    adresse: '7 quai de la Marine',
    ville: 'Sète',
    code_postal: '34200',
    latitude: 43.4053,
    longitude: 3.6939,
    surface_toit_m2: 62.0,
    nb_panneaux_recommande: 10,
    production_annuelle_kwh: 3950,
    heures_ensoleillement: 2720,
    orientation_principale: 'Sud-Ouest',
    score_solaire: 87,
    qualite_imagerie: 'HIGH',
    panneaux_detectes: 'oui',
    date_photo_satellite: 'mai 2024',
    puissance_kwc: 4.05,
    cout_installation_ttc: 9800,
    aides_totales: 950,
    reste_a_charge: 8850,
    economie_annuelle: 1140,
    temps_retour_ans: 7.8,
    co2_evite_kg_an: 226,
    statut: 'visite_planifiee',
    notes: 'Visite technique RDV mardi 10h.',
    proposition_id: 'prop_demo_002',
    proposition_html: null,
    proposition_vue_at: null,
  },
  {
    id: 'demo-3',
    created_at: new Date(now - 12 * day).toISOString(),
    updated_at: new Date(now - 12 * day).toISOString(),
    nom: 'Bernard',
    prenom: 'Sophie',
    email: 'sophie.bernard@example.fr',
    telephone: '06 34 56 78 90',
    adresse: '23 avenue de la Mer',
    ville: 'Lunel',
    code_postal: '34400',
    latitude: 43.6776,
    longitude: 4.1370,
    surface_toit_m2: 95.0,
    nb_panneaux_recommande: 14,
    production_annuelle_kwh: 5680,
    heures_ensoleillement: 2640,
    orientation_principale: 'Sud',
    score_solaire: 95,
    qualite_imagerie: 'HIGH',
    puissance_kwc: 5.67,
    cout_installation_ttc: 13800,
    aides_totales: 0,
    reste_a_charge: 13800,
    economie_annuelle: 1610,
    temps_retour_ans: 8.6,
    co2_evite_kg_an: 324,
    statut: 'signe',
    notes: 'Contrat signé. Installation prévue semaine 28.',
    proposition_id: 'prop_demo_003',
    proposition_html: null,
    proposition_vue_at: null,
  },
  {
    id: 'demo-4',
    created_at: new Date(now - 1 * day).toISOString(),
    updated_at: new Date(now - 1 * day).toISOString(),
    nom: 'Lefebvre',
    prenom: 'Thomas',
    email: 'thomas.lefebvre@example.fr',
    telephone: '06 45 67 89 01',
    adresse: '5 boulevard du Maréchal Joffre',
    ville: 'Palavas-les-Flots',
    code_postal: '34250',
    latitude: 43.5283,
    longitude: 3.9311,
    surface_toit_m2: 54.0,
    nb_panneaux_recommande: 9,
    production_annuelle_kwh: 3520,
    heures_ensoleillement: 2700,
    orientation_principale: 'Sud-Est',
    score_solaire: 81,
    qualite_imagerie: 'MEDIUM',
    puissance_kwc: 3.65,
    cout_installation_ttc: 8900,
    aides_totales: 805,
    reste_a_charge: 8095,
    economie_annuelle: 1010,
    temps_retour_ans: 8.0,
    co2_evite_kg_an: 201,
    statut: 'nouveau',
    notes: 'Premier contact via formulaire site. À rappeler.',
    proposition_id: 'prop_demo_004',
    proposition_html: null,
    proposition_vue_at: null,
  },
  {
    id: 'demo-5',
    created_at: new Date(now - 20 * day).toISOString(),
    updated_at: new Date(now - 20 * day).toISOString(),
    nom: 'Garcia',
    prenom: 'Isabelle',
    email: 'isabelle.garcia@example.fr',
    telephone: '06 56 78 90 12',
    adresse: '18 rue Émile Jamais',
    ville: 'Nîmes',
    code_postal: '30000',
    latitude: 43.8367,
    longitude: 4.3601,
    surface_toit_m2: 88.0,
    nb_panneaux_recommande: 13,
    production_annuelle_kwh: 5200,
    heures_ensoleillement: 2580,
    orientation_principale: 'Sud',
    score_solaire: 89,
    qualite_imagerie: 'HIGH',
    puissance_kwc: 5.26,
    cout_installation_ttc: 12750,
    aides_totales: 0,
    reste_a_charge: 12750,
    economie_annuelle: 1480,
    temps_retour_ans: 8.6,
    co2_evite_kg_an: 297,
    statut: 'perdu',
    notes: 'Prospect a choisi un concurrent (prix).',
    proposition_id: 'prop_demo_005',
    proposition_html: null,
    proposition_vue_at: null,
  },
];

export function demoStats(): DashboardStats {
  const ca_pipeline = demoProspects
    .filter(
      (p) =>
        p.statut === 'proposition_envoyee' ||
        p.statut === 'visite_planifiee',
    )
    .reduce((sum, p) => sum + (p.cout_installation_ttc ?? 0), 0);

  const ca_signe = demoProspects
    .filter((p) => p.statut === 'signe')
    .reduce((sum, p) => sum + (p.cout_installation_ttc ?? 0), 0);

  return {
    total_prospects: demoProspects.length,
    total_analyses: demoProspects.filter(
      (p) => p.production_annuelle_kwh !== null,
    ).length,
    total_propositions: demoProspects.filter(
      (p) => p.statut === 'proposition_envoyee',
    ).length,
    total_signes: demoProspects.filter((p) => p.statut === 'signe').length,
    ca_pipeline,
    ca_signe,
    roi_moyen_ans: 8.2,
  };
}
